import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Advice Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased mx-auto p-0 box-border max-h-screen max-w-[90rem] flex  items-center justify-center mt-[7.5rem] md:mt-56`}
      >
        {children}
      </body>
    </html>
  );
}
